version: "3.9"

networks:
  app-network:
    driver: bridge

services:

  # -------- API GATEWAY --------
  api_gateway:
    image: nginx:latest
    container_name: api_gateway
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - user_manager
      - data_collector
    networks:
      - app-network
  

  # -------- USER MANAGER --------
  user_manager:
    build: ./user_manager
    container_name: user_manager
    expose:
      - "8081"
      - "50051"
    environment:
      - DATABASE_URL=postgresql://user:password@userdb:5432/userdb
    depends_on:
      - userdb
    networks:
      - app-network

  # -------- DATA COLLECTOR --------
  data_collector:
    build: ./data_collector
    container_name: data_collector
    expose:
      - "8082"
    environment:
      - DATABASE_URL=postgresql://user:password@datadb:5432/datadb
      - USER_MANAGER_HOST=user_manager
      - USER_MANAGER_PORT=50051
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    depends_on:
      - datadb
      - user_manager
      - kafka
    networks:
      - app-network

  # -------- DATABASES --------
  userdb:
    image: postgres:15
    container_name: userdb
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: userdb
    ports:
      - "5433:5432"
    volumes:
      - userdb_data:/var/lib/postgresql/data

  datadb:
    image: postgres:15
    container_name: datadb
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: datadb
    ports:
      - "5434:5432"
    volumes:
      - datadb_data:/var/lib/postgresql/data

  # -------- KAFKA --------
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  # -------- ALERT SYSTEM --------
  alert_system:
    build: ./alert_system
    container_name: alert_system
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - DATABASE_URL=postgresql://user:password@datadb:5432/datadb
    depends_on:
      - kafka
      - datadb

  # -------- ALERT NOTIFIER --------
  alert_notifier:
    build: ./alert_notifier
    container_name: alert_notifier
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    depends_on:
      - kafka

volumes:
  userdb_data:
  datadb_data:
